language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - develop
    - feature/travis

services:
  - MySQL
  - PostgreSQL

env:
#  Travis give a TemplateDoesNotExist exception with django==1.6.x
#  - TOXENV=py27-d16-pg
#  - TOXENV=py27-d16-sqlite
#  - TOXENV=py27-d16-mysql
  - TOXENV=py27-d17-pg
  - TOXENV=py27-d17-sqlite
  - TOXENV=py27-d17-mysql
  - TOXENV=py27-d18-pg
  - TOXENV=py27-d18-sqlite
  - TOXENV=py27-d18-mysql
  - TOXENV=py27-d19-pg
  - TOXENV=py27-d19-sqlite
  - TOXENV=py27-d19-mysql
  - TOXENV=py33-d17-pg
  - TOXENV=py33-d17-sqlite
  - TOXENV=py33-d18-pg
  - TOXENV=py33-d18-sqlite
  - TOXENV=py34-d17-pg
  - TOXENV=py34-d17-sqlite
  - TOXENV=py34-d18-pg
  - TOXENV=py34-d18-sqlite
  - TOXENV=py34-d19-pg
  - TOXENV=py34-d19-sqlite
#  - TOXENV=py35-d19-pg
#  - TOXENV=py35-d19-sqlite

install:
  - pip install tox coverage coveralls>=0.5

script:
  - tox -e $TOXENV --recreate -- -vv --capture=no --cov=concurrency --cov-report=xml --cov-config=tests/.coveragerc

before_success:
  - coverage erase

after_success:
  - coverage combine
  - coveralls

